version: "3.5"
services:
  app:
    container_name: app
    restart: always
    build: backend
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
#      MONGO_INITDB_ROOT_USERNAME: myuser
#      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/mydatabase --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
