version: "3"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
